### ISSUE TITLE
Change tile server directory

### ISSUE THREAD

**Issue by rushgeo** [digital-antiquity/skope#3]
We're having an NFS mounting issue right now. The readonly mount of `/project/skope` works, but the rw mount of `/project/web` is not working at the moment.

I think that the tiles are being served from `/project/web`, but I can't find where in this repo that is set up (or I'd submit a pull request). If we can change it to serve from /project/skope/web instead, it would make more sense long term to only need the readonly mount in the prototype VM.

**Comment by abrin** [comment]
Hi Johnathan,
  The tiles are served off of the nginx config using aliases. You should be able to just change that and the restart nginx.  I can try and take care of it later today, but we’re off today and I’m not sure if my local machine has the right ssh keys.  Otherwise, Monday.
- adam

**Comment by abrin** [comment]
Never heard back from you, so I made the change this morning.
